image: docker
services:
  - docker:dind

stages:
  - development
  # - production

development:
  stage: development
  only:
    - development
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no root@qppfpwydmc "cd uneed-guide-react-frontend && git pull && docker-compose down && docker-compose up -d --build"
    - echo "Application successfully deployed."
  when: manual
# production:
#   stage: production
#   only:
#     - main
#   before_script:
#     - apk add openssh-client
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#   script:
#     - echo "Deploying application..."
#     - ssh -o StrictHostKeyChecking=no root@uneedguide.com "cd uneed-guide-react-frontend && git pull && docker-compose down && docker-compose up -d --build"
#     - echo "Application successfully deployed."
#   when: manual
