image: docker
services:
  - docker:dind

stages:
  - test
  - demo
  # - production

test:
  stage: test
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_TEST" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no root@test.uneedguide.com
    - cd ~/test/uneed-guide-react-frontend
    - docker-compose -f ./config/docker/test.compose.yml down --remove-orphans
    - docker-compose -f ./config/docker/test.compose.yml up -d --build
    - echo "Application successfully deployed."
  when: manual

demo:
  stage: demo
  only:
    - development
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEMO" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no root@demo.uneedguide.com
    - cd ~/demo/uneed-guide-react-frontend
    - docker-compose -f ./config/docker/demo.compose.yml down --remove-orphans
    - docker-compose -f ./config/docker/demo.compose.yml up -d --build
    - echo "Application successfully deployed."
  when: manual
# production:
#   stage: production
#   only:
#     - main
#   before_script:
#     - apk add openssh-client
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#   script:
#     - echo "Deploying application..."
#     - ssh -o StrictHostKeyChecking=no root@uneedguide.com "cd uneed-guide-react-frontend && git pull && docker-compose down && docker-compose up -d --build"
#     - echo "Application successfully deployed."
#   when: manual
