image: docker
services:
  - docker:dind

stages:
  - test
  - demo

test:
  stage: test
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_TEST" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no root@test.uneedguide.com "cd test/uneed-guide-react-frontend && git pull && git checkout $CI_COMMIT_BRANCH && docker-compose -f ./config/docker/test.compose.yml down &&  docker-compose -f ./config/docker/test.compose.yml up -d --build"
    - echo "Application successfully deployed."
  when: manual

demo:
  stage: demo
  only:
    - development
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEMO" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no root@test.uneedguide.com "cd demo/uneed-guide-react-frontend && git pull && git checkout development && docker-compose -f ./config/docker/demo.compose.yml down &&  docker-compose -f ./config/docker/demo.compose.yml up -d --build"
    - echo "Application successfully deployed."
  when: manual
